---
- copy:
    src: "{{ item }}"
    dest: /home/vagrant/
    owner: vagrant
    group: vagrant
    mode: 0755
  with_items:
      - dockerfile_web
      - docker_web.yml
      - hosts
      - roles

- name: docker image build
  shell: "docker image build -t web -f /home/vagrant/dockerfile_web ."
