---
- name: docker run
  hosts: localhost
  connection: local
  become: yes
  roles:
    - docker_web

- name: local-tks001起動
  hosts: docker_web
  connection: docker
  become: yes
  tasks:
  - service: name=httpd enabled=yes state=started
  - git: repo=https://github.com/hmkoba/web.git dest=/var/www/html
