FROM centos:7
RUN yum -y update
RUN yum -y install wget epel-release
RUN yum reinstall -y glibc-common
RUN yum -y install httpd

RUN wget http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN rpm -Uvh ./remi-release-7.rpm
RUN sed -i '4a priority=1' /etc/yum.repos.d/remi-php71.repo
RUN yum -y install --enablerepo=remi-php71 php php-fpm php-mcrypt php-cli php-common php-devel php-gd php-mbstring php-mysqlnd php-opcache php-pdo php-pear php-pecl-apcu php-pecl-zip php-process php-xml

RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install git2u yum-utils
RUN yum-config-manager --disable ius

RUN yum -y install sudo
RUN yum clean all

# Create user
RUN useradd docker
RUN passwd -f -u docker
RUN echo "docker ALL=(ALL) ALL" >> /etc/sudoers.d/docker

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
